---
name: main

on:
  push:
    branches: [ "main" ]
    tags: ['*']
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Build example'
      if: ${{ ! startsWith(github.event.ref, 'refs/tags/v') }}
      run: |
        cargo build

    - name: 'Run tests'
      if: ${{ ! startsWith(github.event.ref, 'refs/tags/v') }}
      run: |
        cargo test

    - name: 'Release from tags'
      if: startsWith(github.event.ref, 'refs/tags/v')
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        rustup target add x86_64-unknown-linux-gnu
        cargo build --release --target=x86_64-unknown-linux-gnu
        cp -v target/x86_64-unknown-linux-gnu/release/example ./hedge-example
        tar czvf hedge-${GITHUB_REF_NAME}-x86_64-linux.tar.gz hedge-example
        gh release create ${GITHUB_REF_NAME} ./*.tar.gz --generate-notes
